### ISSUE TITLE
Add dynamic update using interval

### ISSUE THREAD

**Issue by hoIIer** [rajasegar/ember-dayjs-helpers#1]
I started to implement some of these in my own project before finding this, do you plan to add the `interval` argument that exists in `ember-moment` so that the helper can optionally self-update it's value dynamically?

https://github.com/stefanpenner/ember-moment#common-optional-named-arguments
https://github.com/stefanpenner/ember-moment/blob/master/addon/helpers/-base.js#L20

**Comment by rajasegar** [comment]
Sounds like a good idea, I haven't thought about it initially. But it will take some time for me to understand and implement the same here. Meanwhile, if you have a PR ready, would be glad to take a look....

**Comment by burritoIand** [comment]
I just added this locally (taken from ember-moment), could throw a pr together soon
```
import Helper from '@ember/component/helper';
import { run } from '@ember/runloop';

export default class HelperBase extends Helper {
  disableInterval = false;

  compute(value, { interval }) {
    if (this.disableInterval) return;

    if (this.intervalTimer) {
      this.clearTimer();
    }

    if (interval) {
      this.intervalTimer = setTimeout(() => {
        run(() => this.recompute());
      }, parseInt(interval, 10));
    }
  }

  clearTimer() {
    clearTimeout(this.intervalTimer);
  }

  destroy() {
    this.clearTimer();
    super.destroy(...arguments);
  }
}
```
